version: '3.8'
services:
  web:
    build:
      context: ./
    volumes:
      - .:/app
    command: npm run dev
    restart: always
    ports:
      - "3001:3000"
    environment:
      NODE_ENV: development
